[package]
name = "rust_clip"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
clipboard-watcher = "0.2.1"
env_logger = "0.11.11"
futures = "0.3.33"
log = "0.4.33"
rusqlite = "0.40.1"
tauri-plugin-global-shortcut = "2.3.2"
tokio = { version = "1.53.0", features = ["full"] }
wayland-clipboard-listener = "0.6.1"

